print('input data siswa')
nisn = input('masukan nisn : ')
nama = input('masukan nama : ')
kelas = input('masukan kelas : ')
alamat = input('masukan alamat : ')
print('nisn yang diinputkan adalah : ', nisn)
print('atas nama : ', nama)
print('kelas', kelas)
print('alamat', alamat)